# more about
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    APP_NAME: "academy-app" 
    ENV_NAME: "production"
    # APP_TAG: "latest"
    AWS_REPOSITORY_REGION: "eu-central-1"

    VERSION_FROM_GIT: "${CODEBUILD_RESOLVED_SOURCE_VERSION}"
    DIR: "${CODEBUILD_SRC_DIR}"
    
    TERRAFORM_VERSION: "1.0.10"
    TERRAGRUNT_VERSION: "0.35.6"
    WORKDIR_TERRAGRUNT_CLUSTER: "providers/${ENV_NAME}/aws_cluster_fargate"

phases:
  install:
    commands:
      # - echo "Install environment"
      # INSTALL JQ
      # INSTALL TERRAFORM
      # INSTALL TERRAGRUNT
      - apt-get install jq
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_386.zip -O terraform.zip --no-verbose
      - unzip terraform.zip
      - chmod u+x terraform
      - mv terraform /usr/local/bin/
      - rm -rf terraform.zip
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -O terragrunt --no-verbose
      - chmod u+x terragrunt
      - mv terragrunt /usr/local/bin/ 
    finally:
      - jq --version
      - terraform -version
      - terragrunt -version
  
  pre_build:
    commands:
      # SET ENV_VAR for project
      # - aws sts get-caller-identity 
      - export AWS_REGISTRY_ID=`aws sts get-caller-identity | jq -r '.Account'`
      - export AWS_REPOSITORY_NAME=`${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REPOSITORY_REGION}.amazonaws.com/${APP_NAME}-${ENV_NAME}`
      - export AWS_APP_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - env | grep "AWS"
  
  build:
    commands:
      - echo Build with git hooks
      # - echo git commit is - ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - ls -la
      - cd app
      - ls -la
      - make build-app APP_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - cd ${CODEBUILD_SRC_DIR}  
      - terragrunt plan --terragrunt-working-dir ${WORKDIR_TERRAGRUNT_CLUSTER}  -var="app_tag=${AWS_APP_TAG}" 
      - terragrunt apply --terragrunt-working-dir ${WORKDIR_TERRAGRUNT_CLUSTER} -var="app_tag=${AWS_APP_TAG}" -auto-approve 

  post_build:
    commands:
      - echo Application avaliable
      - aws elbv2 describe-load-balancers | jq -r '.LoadBalancers[].DNSName' 
    
  