# more about
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    NAME: "blue-app"
    ENV: "developer-mode"
    VERSION_FROM_GIT: "${CODEBUILD_RESOLVED_SOURCE_VERSION}"
    DIR: "${CODEBUILD_SRC_DIR}"


phases:
  # pre_build:
  #   commands:
  #   # some...
  #   - echo "We prepare to work"
  #   - echo "version is - ${VERSION}"
  #   - echo "workdir is - ${DIR}"
  #   - echo ${CODEBUILD_SRC_DIR}
  #   - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION}
  #   - echo "go to next step"
  #   finally: echo "I'm always run. Even if jobs was falls "

  # install:
    # commands:
      # - apt-get install tree
  #   # some....
  #   - echo "Install environment"
  #   - echo "go to next step"

  build:
    commands:
    # some....
    - echo Build with git hooks
    - echo Manual build-method
    - echo git commit is - ${CODEBUILD_RESOLVED_SOURCE_VERSION}
    - ls -la
    - cd app
    - ls -la
    - make build-app APP_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}

  # post_build:
  #   commands:
  #   # some...
  #   - echo "Send info messages"
  #   - echo "finish"

  